website/anwers/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from learn import views

urlpatterns = [
    path('', views.index, name='index'),
    path('learn/', include('learn.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/learn/urls.py
from django.contrib import admin
from django.urls import path, include
from learn import views

app_name = 'learn'

urlpatterns = [
	path('', views.learn_base, name="learn_base"),
	path('index', views.learn_base, name='index'),
	path('maths/', views.maths, name='maths'),
	path('astronomy/', views.astronomy, name='astronomy'),
	path('physics/', views.physics, name='physics'),
	path('maths/linear_algebra', views.maths_linear_algebra, name='linear algebra'),
	path('login/', views.user_login, name='user_login'),
	path('register/', views.user_register, name='user_register'),
]

website/learn/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save

class LearnerUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	is_user_admin = models.BooleanField(default=False, null=False)

	class Meta:
		verbose_name_plural = 'Users'

	def __str__(self):
		return self.user.username

website/learn/forms.py
from django import forms
from learn.models import *
from django.contrib.auth.models import User

class LearnerUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'password', 'email',)

		widgets = {
			'username' : forms.TextInput(attrs={'placeholder' : 'Username', 'class' : 'input-login'}),
			'password' : forms.PasswordInput(attrs={'placeholder' : 'Password', 'class' : 'input-login'}),
			'email' : forms.TextInput(attrs={'placeholder' : 'Email', 'class' : 'input-login'}),
		}

		help_texts = {
			'username' : None,
			'password' : None,
			'email' : None,
		}

		labels = {
			'username' : "",
			'password' : "",
			'email' : "",
		}

	def __init__(self, *args, **kwargs):
		super(LearnerUserForm, self).__init__(*args, **kwargs)
		self.fields['email'].required = False

website/learn/views.py
from re import template
# from unittest import loader
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from learn.forms import LearnerUserForm 
from django.contrib.auth import authenticate, login, logout


def index(request):
	context_dict = {}
	return render(request, 'learn/index.html', context=context_dict)

def physics(request):
	context_dict = {

		'topic_title': 'Physics',
		'index': 'phys',

		'sub_topics': [
		{
        'title': 'Thermal Physics',
        'image': 'Thermal',
        'url': 'thermal_physics',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Newtonian Dynamics',
        'image': 'Newtonian',
        'url': 'newtonian_dynamics',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
     	},
      	{
        'title': 'Oscillating Systems',
        'image': 'Oscillating_Systems',
        'url': 'oscillating_systems',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Electricity and Magnetism',
        'image': 'Electricity',
        'url': 'electricity_magnetism',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Physics of Solids',
        'image': 'POS',
        'url': 'physics_of_solids',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Nuclear and Particle Physics',
        'image': 'NPP',
        'url': 'nuclear_particle_physics',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
     	},
      	{
        'title': 'Optics',
        'image': 'Optics',
        'url': 'optics',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Quantum and Classical Waves',
        'image': 'Quantum_Waves',
        'url': 'quantum_classical_waves',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	}]
	}
	return render(request, 'learn/topic.html', context=context_dict)


def maths(request):
	context_dict = {

		'topic_title': 'Maths',
		'index': 'maths',

		'sub_topics': [
		{
        'title': 'Linear Algebra',
        'image': 'Linear_Algebra',
        'url': 'linear_algebra',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Abstract Algebra and Groups',
        'image': 'Abstract_Algebra',
        'url': 'abstract_algebra_groups',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
     	},
      	{
        'title': 'Real Analysis',
        'image': 'Real_Analysis',
        'url': 'real_analysis',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Multivariable Calculus',
        'image': 'Multivariable_Calculus',
        'url': 'multivariable_calculus',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Mechanics',
        'image': 'Mechanics',
        'url': 'mechanics',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Mathimatical Methods & Modelling',
        'image': 'Mathematical_Models',
        'url': 'mathematical_modelling',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
     	}]
	}
	return render(request, 'learn/topic.html', context=context_dict)


def computerScience(request):
	context_dict = {

		'topic_title': 'Computer Science',
		'index': 'comp',

		'sub_topics': [
		{
        'title': 'Text as Data',
        'image': 'Linear_Algebra',
        'url': 'text_as_data',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. Optio accusantium, vel praesentium voluptatum explicabo pariatur officia modi quas earum consectetur dolar . Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet voluptatum impedit fugit sit, corrupti rem, quam iusto, excepturi velit exercitationem atque consequuntur consectetur eum nam facilis? Minima asperiores quibusdam nemo!',
      	},
      	{
        'title': 'Programming Languages',

website/templates/learn/base.html
<!DOCTYPE html>
{% load static %}
<html> 
	<head>
		<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
		<script src="https://kit.fontawesome.com/1112a67421.js" crossorigin="anonymous"></script>
		<script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    	<script type="text/javascript" src="{% static 'js/placeholder.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/placeholder.css' %}">
		{% block extra_links %}
		{% endblock %}

		<title>
			{% block title_block %}
				base
			{% endblock %}
		</title>
	</head>


	<body>
		<div class="grid">
		{% block navbar_block %}
			<div class="left-box">
				<div class="nav-bar">
					<ul class="nav-list">
                        <a href="{% url 'learn:learn_base' %}" id="Home"><i class="fa-solid fa-font" id="Home"></i></a>
						<li class="nav-bar-button"><i class="fa-solid fa-code logo" id="bracket"></i><a class="title-slide" href=# id="okay">Computing Science</a></li>
						<li class="nav-bar-button"><i class="fa-solid fa-atom logo" id="atom" ></i><a class="title-slide" href=#>Physics</a></li>
						<li class="nav-bar-button"><i class="fa-solid fa-calculator logo" id="calc" ></i><a class="title-slide" href="{% url 'learn:maths' %}">Maths</a></li>
                        <a href="{% url 'learn:user_login' %}" id="logIn">Login</a>
					</ul>						
				</div>
			</div>
		{% endblock %}
			<div class="main-content">
				{% block body_block %}
			
				{% endblock %}
			</div>
				
		</div>
	</body>

</html>

website/templates/learn/index.html
{% extends 'learn/base.html' %}
{% load static %}

{% block title_block %}
	Master branch
{% endblock %}

{% block body_block %}
	Master branch
{% endblock %}

website/templates/learn/login.html
{% load static %}

{% block title_block %}
	Login
{% endblock %}

{% block extra_links %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block body_block %}

	<div class="frame"></div>
        <div class="container grid">
            <form id="login_form" method="post" action="{% url 'learn:user_login' %}">
				<div class="authentication-form">
					{% csrf_token %}
					<h1>Log In</h1>
					<p class="p-login p-input"><input type="text" name="username" value="" size="40" placeholder="Username" /></p> 
					<p class="p-login p-input"><input type="password" name="password" value="" size="20" placeholder="Password" /></p>
					<p class="p-login p-submit"><input type="submit" value="Submit" /></p>
				</div>
			</form>
            <div class="signUp">
                <p>Click here to register if you are a new member!</p>
                <a href="{% url 'learn:user_register' %}"> Register </a>
            </div>
        </div>
{% endblock %}

website/templates/learn/register.html
<!DOCTYPE html>
{% load static %}
<html> 
	<head>
		<meta charset="utf-8" />
		<link rel="stylesheet" href="{% static 'css/register.css' %}">
		{% block extra_links %}
		{% endblock %}
		<title>
			Register
		</title>
	</head>


	<body>
	{% block body_block %}
		{% if registered %}
			<div id="registered-container">
				<span class="tick">
					<svg ><polyline points="10 53 45 90 100 20"></polyline></svg>
				</span>
				<p>Thank you for joining us!</p>
				<a href="{% url 'learn:learn_base' %}">Return Home</a>
			</div>	
		{% else %}
			<form id="register_form" method="post" action="{% url 'learn:user_register' %}">
				<div class="authentication-register-div">
					<h1>Register</h1>
					{% csrf_token %}
					{{ learner_user_form.as_p }}
					<input id="register-submit" type="submit" value="Register" />
				</div>
			</form>
		{% endif %}
	{% endblock %}	
	</body>

</html>

website/templates/learn/sub-topic.html
{% extends 'learn/base.html' %}
{% load static %}

{% block title_block %}
	{{ sub_topic_title }}
{% endblock %}

{% block extra_links %}
	<link rel="stylesheet" href="{% static 'css/topics_placeholder.css' %}">
	<link rel="stylesheet" href="{% static 'css/subtopics_placeholder.css' %}">
{% endblock %}

{% block body_block %}
    <div class="grid-container">
        <div class="topic-title grid-col-span-2"><h1>{{sub_topic_title}}</h1></div>
        <div class="index_sub grid-col-span-2 ">
        {% for x in sub_sub_topics %}
            <a class="sub-sub-index" href="{% url 'learn:linear algebra' %}"><p>{{x.title}}</p></a>
        {% endfor %}
        </div>
        {% for x in sub_sub_topics %}
        <a class="sub-sub-topic ">
            <h2>{{x.title}}</h2>
            <div class="sub-sub-container">
                <span> video </span>
                <p class="sub-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, nobis at. Ipsa vel ut assumenda modi culpa. </p>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}

website/templates/learn/topic.html
{% extends 'learn/base.html' %}
{% load static %}

{% block title_block %}
	{{ topic_title }}
{% endblock %}

{% block extra_links %}
	<link rel="stylesheet" href="{% static 'css/topics_placeholder.css' %}">
	<link rel="stylesheet" href="{% static 'css/Physics.css' %}">
	<link rel="stylesheet" href="{% static 'css/Maths.css' %}">
	<link rel="stylesheet" href="{% static 'css/Comp_Sci.css' %}">
{% endblock %}


{% block body_block %}
	<div class="grid-container">
		<div class="topic-title grid-col-span-2"><h1>{{topic_title}}</h1></div>
		<div class="index_{{index}} grid-col-span-2">
		{% for x in sub_topics %}
			<a class="sub-sub" href="{% url 'learn:linear algebra' %}"><img src="/static/Images/{{x.image}}.png"><p>{{x.title}}</p></a>
		{% endfor %}
		</div>
		<div class=" media-scroller " id="pop-videos">
			<div class="media-element"></div>
			<div class="media-element" ></div>
			<div class="media-element"></div>
			<div class="media-element"></div>
			<div class="media-element"></div>
		</div>
		<div id="forum"></div>
		{% for x in sub_topics %}
		<div id="{{x.image}}"class="sub-topic grid-col-span-2">
			<h2>{{x.title}}</h2>
			<div id="pre-learn">
				<a href="#"><p>LEARN</p></a>
				<p class="description"> {{x.description}}</p>
			</div>
			<div id="suggest-vid" class="media-scroller"></div>
		</div>
		{% endfor %}
	</div>
{% endblock %}